// exercise.dart

import 'package:hive_flutter/hive_flutter.dart';

part 'exercise.g.dart'; // REQUIRED: This is generated by build_runner

@HiveType(typeId: 0) // Unique ID for this type/class
class Exercise extends HiveObject { // Extend HiveObject for automatic ID and management
  
  @HiveField(0) // Start field indexing from 0
  final String? id; 
  @HiveField(1)
  final String name;
  @HiveField(2)
  final String muscles; 
  @HiveField(3)
  final int sets;
  @HiveField(4)
  final int reps;
  @HiveField(5)
  final String unit; 
  @HiveField(6)
  final bool isCustom;

  // --- FIELDS FOR OFFLINE-FIRST ---
  @HiveField(7)
  final String syncStatus; 
  @HiveField(8)
  final int updatedAt;     
  @HiveField(9)
  final bool isDeleted; // Used for soft deletion (syncing deletions)

  Exercise({
    this.id, 
    required this.name,
    required this.muscles,
    required this.sets,
    required this.reps,
    this.unit = 'reps',
    this.isCustom = false,
    this.syncStatus = 'synced',
    this.updatedAt = 0,
    this.isDeleted = false, // Initialize soft delete flag
  });
  
  // --- CopyWith method is CRITICAL for immutable state management ---
  // The copyWith method remains largely the same, just including the new field
  Exercise copyWith({
    String? id,
    String? name,
    String? muscles,
    int? sets,
    int? reps,
    String? unit,
    bool? isCustom,
    String? syncStatus,
    int? updatedAt,
    bool? isDeleted, // Include new field
  }) {
    return Exercise(
      id: id ?? this.id,
      name: name ?? this.name,
      muscles: muscles ?? this.muscles,
      sets: sets ?? this.sets,
      reps: reps ?? this.reps,
      unit: unit ?? this.unit,
      isCustom: isCustom ?? this.isCustom,
      syncStatus: syncStatus ?? this.syncStatus,
      updatedAt: updatedAt ?? this.updatedAt,
      isDeleted: isDeleted ?? this.isDeleted, // Handle new field
    );
  }

  // toMap and fromMap are still needed for Firebase integration

  Map<String, dynamic> toMap() {
    return {
      'name': name,
      'muscles': muscles,
      'sets': sets,
      'reps': reps,
      'unit': unit,
      'isCustom': isCustom,
      'syncStatus': syncStatus,
      'updatedAt': updatedAt,
      'isDeleted': isDeleted,
    };
  }

  factory Exercise.fromMap(Map<String, dynamic> map, {String? id}) {
    return Exercise(
      id: id ?? map['id'],
      name: map['name'] ?? '',
      muscles: map['muscles'] ?? '',
      sets: map['sets'] ?? 0,
      reps: map['reps'] ?? 0,
      unit: map['unit'] ?? 'reps',
      isCustom: map['isCustom'] ?? false,
      syncStatus: map['syncStatus'] ?? 'synced',
      updatedAt: map['updatedAt'] ?? 0,
      isDeleted: map['isDeleted'] ?? false,
    );
  }
}