name: fitness_app_mock
description: UI mockup for a fitness app (Flutter)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  fl_chart: ^0.69.0
  table_calendar: ^3.2.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  image_picker: ^1.0.7
  firebase_storage: ^13.0.4
  cloud_firestore: ^6.1.0

flutter:
  uses-material-design: true
