// local_db_service.dart

import 'package:flutter/foundation.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'misc/exercise.dart';
// Note: You must ensure 'exercise.g.dart' is generated for the ExerciseAdapter

const String _exerciseBoxName = 'exercises';

class LocalDbService {
  
  late Box<Exercise> _exerciseBox;

  // 1. Initialization method
  Future<void> init() async {
    // 1. Initialize Hive and register the adapter generated by build_runner
    await Hive.initFlutter();
    if (!Hive.isAdapterRegistered(ExerciseAdapter().typeId)) {
      Hive.registerAdapter(ExerciseAdapter());
    }
    
    // 2. Open the Box (equivalent to a table/collection)
    _exerciseBox = await Hive.openBox<Exercise>(_exerciseBoxName);
    
    debugPrint("Hive DB initialized: Box '$_exerciseBoxName' opened.");
  }

  // 2. READ: This is the main source of truth for the UI
  Future<List<Exercise>> getAllExercises() async {
    // Hive's toList() is typically fast enough that we don't need a delay
    // Filter out items marked for soft deletion
    return _exerciseBox.values.where((ex) => !ex.isDeleted).toList();
  }

  // 3. WRITE: Used when creating a new local record or syncing from Firebase
  Future<void> saveExercise(Exercise ex) async {
    // We use the Exercise.id (which is the Firebase/local UUID) as the Hive key
    // This allows us to use the put() method for both INSERT (if key is new) 
    // and UPDATE (if key exists).
    if (ex.id == null) {
      // This should ideally be prevented by the Notifier generating an ID,
      // but good defensive coding to throw if it happens.
      throw Exception("Cannot save Exercise without an ID.");
    }
    
    await _exerciseBox.put(ex.id!, ex);
    
    debugPrint("Hive DB saved/updated exercise: ${ex.name}, Status: ${ex.syncStatus}");
  }

  // 4. READ PENDING: Used by the Sync Manager to find unsynced data
  Future<List<Exercise>> getPendingExercises() async {
    // Filter the box for records with the 'pending' syncStatus
    return _exerciseBox.values.where((ex) => ex.syncStatus == 'pending').toList();
  }
}

// Instantiate the service for use in Riverpod providers
final localDbService = LocalDbService();