// template.dart

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:hive_flutter/hive_flutter.dart'; // NEW
import '../exercise/exercise_block.dart';

part 'template.g.dart'; // REQUIRED: Generated by build_runner

@HiveType(typeId: 1) // Must be a unique typeId (Exercises used 0)
class Template extends HiveObject {
  
  @HiveField(0)
  final String? id;
  @HiveField(1)
  final String name;
  @HiveField(2)
  final List<ExerciseBlock> exercises;
  @HiveField(3)
  final bool isCustom;

  // --- NEW FIELDS FOR OFFLINE-FIRST ---
  @HiveField(4)
  final String syncStatus; // 'synced', 'pending', 'error'
  @HiveField(5)
  final int updatedAt;     // Timestamp for conflict resolution
  @HiveField(6)
  final bool isDeleted; // Soft delete flag

  Template({
    this.id,
    required this.name,
    required this.exercises,
    this.isCustom = false,
    this.syncStatus = 'synced',
    this.updatedAt = 0,
    this.isDeleted = false,
  });

  // --- CopyWith method is CRITICAL for immutable state management ---
  Template copyWith({
    String? id,
    String? name,
    List<ExerciseBlock>? exercises,
    bool? isCustom,
    String? syncStatus,
    int? updatedAt,
    bool? isDeleted,
  }) {
    return Template(
      id: id ?? this.id,
      name: name ?? this.name,
      exercises: exercises ?? this.exercises,
      isCustom: isCustom ?? this.isCustom,
      syncStatus: syncStatus ?? this.syncStatus,
      updatedAt: updatedAt ?? this.updatedAt,
      isDeleted: isDeleted ?? this.isDeleted,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'name': name,
      'isCustom': isCustom,
      'exercises': exercises.map((e) => e.toMap()).toList(),
      'syncStatus': syncStatus,
      'updatedAt': updatedAt,
      'isDeleted': isDeleted,
    };
  }

  factory Template.fromDoc(DocumentSnapshot<Map<String, dynamic>> doc) {
    final data = doc.data() ?? {};
    return Template(
      id: doc.id,
      name: (data['name'] as String?) ?? '',
      isCustom: (data['isCustom'] as bool?) ?? false,
      exercises: (data['exercises'] as List<dynamic>? ?? [])
          .map((e) => ExerciseBlock.fromMap(Map<String, dynamic>.from(e)))
          .toList(),
      syncStatus: (data['syncStatus'] as String?) ?? 'synced',
      updatedAt: (data['updatedAt'] as int?) ?? 0,
      isDeleted: (data['isDeleted'] as bool?) ?? false,
    );
  }
  
  factory Template.fromMap(Map<String, dynamic> map, {String? id}) {
    return Template(
      id: id,
      name: (map['name'] as String?) ?? '',
      isCustom: (map['isCustom'] as bool?) ?? false,
      exercises: (map['exercises'] as List<dynamic>? ?? [])
          .map((e) => ExerciseBlock.fromMap(Map<String, dynamic>.from(e)))
          .toList(),
      syncStatus: (map['syncStatus'] as String?) ?? 'synced',
      updatedAt: (map['updatedAt'] as int?) ?? 0,
      isDeleted: (map['isDeleted'] as bool?) ?? false,
    );
  }
}

// NOTE: You must also update ExerciseBlock.dart to extend HiveObject and
// use HiveField annotations, as it is nested inside Template!